// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  模板留下的探针命令：用来验证 IPC 通道本身是通的（`docs/STATUS.md` 的 IPC 端到端检查）。
	 * 
	 *  `#[specta::specta]` 是必须的 —— 少了它，`collect_commands!` 会直接编译失败
	 *  （比"前端调不到"这种运行期错误好得多）。
	 */
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	/**
	 *  库在哪、建过没有、开着没有。**只读元数据 + 一个布尔**：不打开库、不创建目录、不要口令。
	 * 
	 *  它**不记日志**：那是一个查询（前端可能反复调），而日志留给状态**变化** ——
	 *  这里没有变化，只有"此刻是什么"。
	 */
	vaultStatus: () => typedError<VaultStatus, VaultError>(__TAURI_INVOKE("vault_status")),
	/**
	 *  解锁：打开已有的库；**没有库就建一个**（文件不存在或 0 字节）。
	 * 
	 *  建 / 开的选择来自 [`plan_for`]，而"开"与"建"仍然是存储层的两条路（plan 0402）——
	 *  这里没有把它们合并成一个"打不开就建"的兜底：那正是实测里"任何口令都能打开一个
	 *  0 字节文件"的那条歧路。
	 * 
	 *  已经解开时返回 [`VaultError::AlreadyUnlocked`]：**不替换、不重复开**。
	 *  检查是 check-then-act：并发调用时两边都会算一次 KDF（约 105 ms）而只有一个成功 ——
	 *  代价照实记，不为它加一套排队逻辑。
	 */
	vaultUnlock: (passphrase: PassphraseInput) => typedError<VaultContents, VaultError>(__TAURI_INVOKE("vault_unlock", { passphrase })),
	/**
	 *  锁定：把解好的连接与口令**一起**丢掉（`Some` → `None`）。
	 * 
	 *  返回"刚才是不是真锁上了一个"：调用方（前端 / 测试）要靠它区分
	 *  "锁上了"与"本来就是锁着的"—— 后者不是错误，但也不该被报成一次状态变化。
	 * 
	 *  抹掉了什么、抹不掉什么：见模块文档的「边界」与 plan 0407 的副本清单。
	 *  口令那一页由 `memsafe` `munmap`（实测 `VmLck` 归零）；SQLCipher 内部的密钥材料
	 *  由 `cipher_memory_security` 在释放时擦零（实测：派生密钥的副本一处不剩）。
	 */
	vaultLock: () => typedError<boolean, VaultError>(__TAURI_INVOKE("vault_lock")),
	/**
	 *  库里主机池的全部行（按名字排序 —— 顺序确定，界面才不会每次刷新换一个样）。
	 * 
	 *  库锁着 → [`VaultError::Locked`]：池在库里，没有别的来路。
	 */
	vaultHosts: () => typedError<HostEntry[], VaultError>(__TAURI_INVOKE("vault_hosts")),
	/**
	 *  打开一个终端会话，输出经 `channel` 以 **raw 字节**送出。
	 * 
	 *  返回的 id 是前端后续 `write_session` / `resize_session` / `close_session` 要用的句柄。
	 * 
	 *  会话**自己结束**时（用户在终端里敲了 `exit`、shell 崩了、PTY 被关掉）由一条收尾线程
	 *  负责：收掉它 + 发 [`SessionEnded`] 让前端关掉那个标签页。
	 */
	openSession: (channel: RawChannel) => typedError<number, IpcError>(__TAURI_INVOKE("open_session", { channel })),
	/**
	 *  打开一个 SSH 终端会话，输出经 `channel` 以 **raw 字节**送出。
	 * 
	 *  与 [`crate::session::open_session`] 的关系：**同一条尾巴**（注册 → 频道 → 收尾线程），
	 *  差的是载体怎么来 —— 本地那条是 `PtyTransport::spawn_default()`，这条是
	 *  "照池里那一行连过去"。
	 * 
	 *  ⚠️ **async**：命令体里有一次会阻塞几秒的握手（最长 `connect_timeout`），而
	 *  同步 command 跑在处理 IPC 请求的那条线程上（挡住它就等于挡住全部 IPC ——
	 *  包括用户回答问题要用的那三条命令）。
	 */
	openSshSession: (channel: RawChannel, hostId: number) => typedError<number, SshIpcError>(__TAURI_INVOKE("open_ssh_session", { channel, hostId })),
	/**  把用户输入（按键字节）送进会话。 */
	writeSession: (handle: number, data: number[]) => typedError<null, IpcError>(__TAURI_INVOKE("write_session", { handle, data })),
	/**  调整会话的窗口尺寸（列 / 行）。 */
	resizeSession: (handle: number, cols: number, rows: number) => typedError<null, IpcError>(__TAURI_INVOKE("resize_session", { handle, cols, rows })),
	/**  关闭会话：显式 kill + wait 收尸，之后这个 id 不再有效。 */
	closeSession: (handle: number) => typedError<null, IpcError>(__TAURI_INVOKE("close_session", { handle })),
	/**  回答一句秘密（口令 / 验证码 / 私钥口令）。 */
	sshPromptCredential: (id: number, secret: PassphraseInput) => typedError<null, PromptError>(__TAURI_INVOKE("ssh_prompt_credential", { id, secret })),
	/**  回答"这把没见过的主机密钥认不认"。 */
	sshPromptHostKey: (id: number, accept: boolean) => typedError<null, PromptError>(__TAURI_INVOKE("ssh_prompt_host_key", { id, accept })),
	/**
	 *  撤销这一问（用户关掉了提示面板）。**不是"接受"的另一种写法**：
	 *  它让连接以"用户取消"结束。
	 */
	sshPromptCancel: (id: number) => typedError<null, PromptError>(__TAURI_INVOKE("ssh_prompt_cancel", { id })),
};

/** Events */
export const events = {
	sessionEnded: makeEvent<SessionEnded>("session_ended"),
	sshPrompt: makeEvent<PromptRequest>("ssh_prompt"),
	sshPromptDismissed: makeEvent<PromptDismissed>("ssh_prompt_dismissed"),
};

/* Types */
/**
 *  认证方式过 IPC 的形状。
 * 
 *  与 `akasha_store::pools::hosts::Auth` 分开：存储 crate **不依赖 specta**
 *  （那是 app 钉住版本的东西），所以这里做一次显式映射 —— 而映射写成穷尽 `match`，
 *  池里加一种认证方式时**这里编译不过**。
 */
export type AuthMethod = "password" | "publicKey" | "agent";

/**  界面看得见的一台主机。 */
export type HostEntry = {
	/**  池里的行 id（`open_ssh_session` 要的就是它）。 */
	id: number,
	/**  用户给这台主机起的名字（池里唯一）。标签页标题用它。 */
	name: string,
	/**  主机名或 IP。 */
	host: string,
	port: number,
	user: string,
	/**  认证方式（池里的取值，见 [`AuthMethod`]）。 */
	auth: AuthMethod,
	/**
	 *  配了哪把钥匙（`keys.id`）。只有 `publickey` 时可能非空 —— 而它也可能是空的
	 *  （走 ssh-agent 的钥匙不在我们的池里）。
	 */
	keyId: number | null,
	/**
	 *  这台主机**经哪台连**（`hosts.jump_id`，plan 0505）。
	 * 
	 *  出现在这里是因为它已经是库里的一列，而"从界面选主机"的人有权知道这一次点下去
	 *  会**经过谁** —— 不然一条跳板链在界面上没有任何痕迹，连不上时也无从判断是目标的问题
	 *  还是跳板的问题。链本身（跳板还有跳板）由连接那条路自己走，界面只看一跳。
	 */
	jumpId: number | null,
};

/**
 *  IPC 边界的错误。
 * 
 *  域边界就在这里：`akasha-core` 与 `akasha-pty` **都不知道 IPC 存在**，所以它们的错误
 *  在这里收敛成一个可序列化的形状（`AGENTS.md` §3.4）。前端能据此区分的只有三件事：
 *  会话不存在 / 载体出错 / 频道句柄无效 —— 再细的分支要等真有 UI 依赖它时再加。
 */
export type IpcError = 
/**  这个会话不存在：已经关闭，或从来没打开过。**两者的处置相同**，故不区分。 */
{ kind: "notFound"; detail: {
	handle: number,
} } | 
/**  载体失败（IO / 能力不支持 / 已关闭）。消息原样来自 `TransportError`。 */
{ kind: "transport"; detail: {
	message: string,
} } | 
/**  传给后端的东西不是合法的频道句柄。 */
{ kind: "channel"; detail: {
	message: string,
} } | 
/**
 *  内部状态不可用（Mutex 中毒，或 core 的 id 装不进句柄）。
 *  **不是用户错误** —— 但也不能 `unwrap`。
 */
{ kind: "internal"; detail: {
	message: string,
} };

/**
 *  口令 / 凭据**经 IPC 进来的形态**（`PassphraseInput`）。
 * 
 *  它是"一句秘密从前端进来"在 IPC 边界上的唯一类型 —— 库解锁（plan 0407）与 SSH 的凭据
 *  提问（plan 0504）共用它。共用而不是各写一个，是因为它的性质正是两者都要的：
 *  它唯一能做的事是 [`PassphraseInput::into_bytes`]。
 * 
 *  刻意**没有** `Debug`：`tracing::info!(?input)` 是**编译错误**，而不是"打码" ——
 *  与 `Passphrase` 同一手法（`AGENTS.md` §3.4）。
 * 
 *  `#[specta(transparent)]` 让它生成成 `string`（线上确实是 JSON 字符串），
 *  前端因此不需要为它手写第二份签名（对比 `RawChannel` 那段：那个需要手写，
 *  因为频道句柄的语义生成器表达不出来）。
 */
export type PassphraseInput = string;

/**
 *  这次提问**不用答了**（超时被撤下）。
 * 
 *  为什么要有它：界面上一份提示不能永远留着 —— 没有人答的那一问在
 *  [`PROMPT_TIMEOUT`] 之后会被撤掉，前端必须**看得见**这件事，否则它会一直显示一个
 *  早已不存在的提问（用户再点"确定"只会得到 `Gone`）。
 */
export type PromptDismissed = {
	id: number,
};

/**
 *  回答提问时可能出的错。
 * 
 *  变体按**前端能做什么**分：`Gone` 什么都不用做（那一问已经超时了，界面自己也收到了
 *  `ssh_prompt_dismissed`），`Invalid` 要用户改一下再提交，`Internal` 只该记日志。
 */
export type PromptError = 
/**  这个编号没有在等的提问：已经超时被撤下，或者已经答过了。 */
{ kind: "gone"; detail: {
	id: number,
} } | 
/**  答案本身不合法（空 / 比一页受保护内存还长）。**不是截断**。 */
{ kind: "invalid"; detail: {
	message: string,
} } | 
/**  内部状态不可用（待答表中毒）。 */
{ kind: "internal"; detail: {
	message: string,
} };

/**
 *  后端要问用户一件事。前端据此打开提示界面。
 * 
 *  两个变体放在同一个事件里，是因为它们**在同一条路上**发生（连接中途、同一个往返机制、
 *  同一个超时）—— 分成两个事件只会让"谁在问"多一份要维护的契约。
 *  ⚠️ 但**策略**完全不同：主机密钥那一问只有"接受 / 拒绝"两个答案（见 `ssh.rs` 的接线），
 *  凭据那一问是一句秘密。
 */
export type PromptRequest = 
/**  一把没见过的服务端主机密钥，请用户核对指纹（ADR-0003 D11）。 */
{ kind: "hostKey"; id: number; host: string; port: number; 
/**  密钥算法（`ssh-ed25519` 一类）—— 与指纹一起显示，用户核对的是指纹。 */
algorithm: string; 
/**  `SHA256:…`，**要用户拿去核对的那串东西**。 */
fingerprint: string } | 
/**  要一句秘密。 */
{ kind: "credential"; id: number; 
/**  `user@host:port`（`SshTarget` 的 `Display`）—— 用户得知道在给谁输口令。 */
target: string; credential: SecretKind; 
/**  直接可以显示给用户的一句话（`CredentialRequest::prompt`）。 */
prompt: string };

/**
 *  前端 raw 字节频道的句柄。
 * 
 *  **线上就是一个字符串**（`__CHANNEL__:<id>`）：tauri 的频道是前端创建、只把 id 递给
 *  后端的东西。所以这里声明成"字符串"而不是 `Channel<Vec<u8>>` —— 后者在 JS 侧是
 *  `number[]`（JSON 数组），是本文件开头说的那条慢路。
 * 
 *  校验在 Rust 侧：解析不出 `<id>` 就报 `IpcError::Channel`，不会静默丢掉输出。
 */
export type RawChannel = string;

/**
 *  **要哪一种凭据** —— 过 IPC 的形态（`akasha-ssh` 的 `CredentialKind` 没有 `specta`）。
 * 
 *  前端用它决定提示语的语气（验证码 / 口令 / 私钥口令），**不决定行为**：
 *  三种都是"一句秘密"，答案的走法完全相同。
 */
export type SecretKind = "loginPassword" | "keyboardInteractive" | "keyPassphrase";

/**
 *  一个会话**自己**结束了：载体（PTY 里的 shell）退出 —— 用户敲了 `exit`、shell 崩了、
 *  PTY 被关掉。总之**不是**"用户关掉了标签页"那条路。
 * 
 *  前端据此关掉对应的标签页：标签页与会话**同生命期**（`docs/scope.md` §5.6），两个方向都要
 *  成立 —— 关标签页 → 丢弃会话（plan 0305）；会话自己走 → 标签页跟着走（本步）。
 */
export type SessionEnded = {
	/**  哪个会话结束了。前端按它找要关掉的那个标签页。 */
	handle: number,
	/**  结局的可读描述（`None` = 这个载体不报结局，或收尾时出了岔子 —— 见 `retire`）。 */
	status: string | null,
};

/**
 *  连接失败的类别。**前端据此决定"要不要让用户核对什么"** —— 不是把消息字符串
 *  拿去匹配（那是最容易在改文案时静默失效的一种判据）。
 */
export type SshFailureKind = 
/**  **服务端的密钥与记下来的不一样**（ADR-0003 D11 的警报，阶段 6 也不重连）。 */
"hostKeyChanged" | 
/**  用户否认了一把没见过的密钥 —— 与上一档分开：那是常态，这是明确拒绝。 */
"hostKeyRejected" | 
/**  没见过这把密钥，而没问成（超时 / 没人可问）。**不是"接受"的近义词**。 */
"hostKeyUnknown" | 
/**  库内的主机密钥缓存用不了（写了 / 读不出）—— 提示里那条"先解锁"多半是它。 */
"hostKeyCache" | 
/**  认证失败：我们有的方式都试过了。 */
"auth" | 
/**  连不上 / 超时 / 通道开不出来。 */
"connect" | 
/**
 *  **跳板这条线断了**（plan 0505）：链成环 / 过长，或者跳板机拒绝转发到目标。
 * 
 *  与 [`SshFailureKind::Connect`] 分开是刻意的：那一档是"我连不上**你挑的那台**"，
 *  这一档是"**跳板机**够不着它"。混在一起用户会去查自己的网络，而问题在对端。
 */
"jump" | 
/**  其余（错误消息里说得清）。 */
"other";

/**  IPC 边界的 SSH 错误。变体按**用户的下一步动作**分（见模块文档）。 */
export type SshIpcError = 
/**  库没解锁。**不连**：信任记录与密钥池都在库里，绕过去就等于把三态判定降成两态。 */
{ kind: "locked" } | 
/**  池里没有这一行（`id` 不存在，或者它引用的密钥不见了）。 */
{ kind: "noSuchHost"; detail: {
	id: number,
} } | 
/**  连接这条路失败。`kind` 是给界面分辨**警报**用的，`message` 是给人看的整句话。 */
{ kind: "failed"; detail: {
	kind: SshFailureKind,
	message: string,
} } | 
/**  内部状态不可用（runtime 起不来、会话表中毒、连接线程起不来）。 */
{ kind: "internal"; detail: {
	message: string,
} };

/**
 *  库文件的状态。**与 `akasha_store::VaultState` 分开**：这是 IPC 类型（要生成 TS），
 *  而存储 crate 不该为了生成 TS 去依赖被 app 钉住版本的 `specta`。
 * 
 *  两边的映射写成穷尽 `match`（下面的 `From`）：存储层加了状态，**这里编译不过** ——
 *  而不是悄悄少一个分支，让前端在一个它不认识的值上做默认动作。
 * 
 *  ⚠️ 这个名字与 `tauri::State` 撞车，所以那几个签名里写全 `tauri::State<'_, Vault>` ——
 *  不为了省几个字把 IPC 类型改名（它已经出现在生成物里）。
 */
export type State = 
/**  文件不存在：还没有建过。解锁会**建一个新的**。 */
"missing" | 
/**
 *  文件在但是 **0 字节**：还没有密钥落在那里（这种文件用什么口令都能"打开"，
 *  见 ADR-0002 §7）。解锁同样会建一个新的。
 */
"empty" | 
/**  有内容。解锁会**打开它**（口令不对就打不开）。 */
"present";

/**
 *  解锁之后读一次四套池的结果。
 * 
 *  它存在的理由不是"给用户看几个数字"，而是让 `AGENTS.md` §7 那条"真实路径走通"
 *  有对象：真 app 上 `invoke` 出来的这份数字，正是**库真的被解开并读通了**的证据
 *  （只有拿到了正确的密钥才读得出行数）。
 */
export type VaultContents = {
	/**
	 *  计数是 `u32` 而不是 `usize`：生成器**拒绝**把 64 位整数导出成 TS
	 *  （BigInt 的精度问题，坑 #32 的同一个坑）。这里不做 `as` 截断，而是 checked 转换。
	 */
	keys: number,
	hosts: number,
	serials: number,
	forwards: number,
};

/**
 *  取库的状态时可能出的错。
 * 
 *  与 `IpcError` 分开：域不同，前端能据此做的动作也不同（这里是"环境或口令的问题"，
 *  而不是"某个会话坏了"）。
 * 
 *  变体按**用户的下一步动作**合并（与 `StoreError::Conflict` 同一个理由）：
 *  版本不对 / 缺表 / 文件在半路被删了，对用户都是"这个库用不了，看消息"。
 */
export type VaultError = 
/**
 *  连数据目录都取不到（既没有便携目录，OS 数据目录也解析失败）。
 * 
 *  ⚠️ **不退回 OS 目录**（`portable.md` §2 第 3 条）：用户以为数据在 U 盘上、
 *  实际落在本地磁盘，比"明确报错"坏得多。
 */
{ kind: "noDataDir" } | 
/**  看文件状态这一步失败了（权限 / IO）。 */
{ kind: "io"; detail: {
	message: string,
} } | 
/**
 *  已经解开了。**不替换**：静默换掉一个正在用的连接，会让"我现在用的是哪把口令"
 *  变成一个没人答得上来的问题。
 */
{ kind: "alreadyUnlocked" } | 
/**
 *  打不开：口令错**或**文件不是本程序的库。SQLCipher 对这两者给同一个
 *  `SQLITE_NOTADB`，我们也不假装能区分（文案因此把两种可能都说出来）。
 */
{ kind: "wrongPassphrase" } | 
/**
 *  空口令。前端本该拦住，但**后端也不接受** —— 空 key 会让 SQLCipher 退化成明文库
 *  （ADR-0002 D5）。
 */
{ kind: "emptyPassphrase" } | 
/**
 *  口令比一页受保护内存还长（`akasha_store::MAX_LEN`）。**不是截断**：
 *  截断会让"口令错了"变成一件没人能解释的事。
 */
{ kind: "passphraseTooLong"; detail: {
	max: number,
} } | 
/**
 *  **内存锁不住**（`mlock` 被拒）：`memsafe` 没有降级路径，所以解锁**不能进行**。
 * 
 *  这条必须是用户能懂的一句话，而不是一个错误码：它是"这台机器上你解不开自己的库"，
 *  下一步动作是查 `ulimit -l` / 容器里的 `RLIMIT_MEMLOCK`，而不是重试。
 */
{ kind: "notLockable"; detail: {
	message: string,
} } | 
/**
 *  库**锁着**，而这条路径需要一个解开的库。
 * 
 *  与 [`VaultError::AlreadyUnlocked`] 是一对：那个说"已经有连接了，别再开一个"，
 *  这个说"还没有连接，先解开"。目前只有 SSH 那条路会走到这里（它的信任记录与
 *  密钥池都在库里），但文案不写"SSH" —— 错误说的是**库的状态**，不是谁在问。
 */
{ kind: "locked" } | 
/**  这个库用不了：版本不认识、缺表、或者文件在半路没了。 */
{ kind: "unusable"; detail: {
	message: string,
} } | 
/**
 *  内部状态不可用（Mutex 中毒、阻塞任务 join 失败）。
 *  **不是用户错误**，但也不能 `unwrap`。
 */
{ kind: "internal"; detail: {
	message: string,
} };

/**  `vault_status` 的返回。 */
export type VaultStatus = {
	/**
	 *  库文件的路径（ADR-0002 D1：与 `config.json` 同一个数据目录）。
	 * 
	 *  它**是**绝对路径，而这与 P2 第 2 条（"库里不存绝对路径"）不冲突：那条禁止的是
	 *  **把路径存进库**（搬家后会静默失效），而这是运行时算出来给用户看的 ——
	 *  顺带回答"我的数据到底在哪"（`portable.md` §4）。
	 */
	path: string,
	state: State,
	/**
	 *  库**开着**没有（解密连接在不在）。与 `state` 是两件事：文件一直在，
	 *  而锁开了、又锁上了。
	 */
	unlocked: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

