// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  模板留下的探针命令：用来验证 IPC 通道本身是通的（`docs/STATUS.md` 的 IPC 端到端检查）。
	 * 
	 *  `#[specta::specta]` 是必须的 —— 少了它，`collect_commands!` 会直接编译失败
	 *  （比"前端调不到"这种运行期错误好得多）。
	 */
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	/**
	 *  库在哪、建过没有、开着没有。**只读元数据 + 一个布尔**：不打开库、不创建目录、不要口令。
	 * 
	 *  它**不记日志**：那是一个查询（前端可能反复调），而日志留给状态**变化** ——
	 *  这里没有变化，只有"此刻是什么"。
	 */
	vaultStatus: () => typedError<VaultStatus, VaultError>(__TAURI_INVOKE("vault_status")),
	/**
	 *  解锁：打开已有的库；**没有库就建一个**（文件不存在或 0 字节）。
	 * 
	 *  建 / 开的选择来自 [`plan_for`]，而"开"与"建"仍然是存储层的两条路（plan 0402）——
	 *  这里没有把它们合并成一个"打不开就建"的兜底：那正是实测里"任何口令都能打开一个
	 *  0 字节文件"的那条歧路。
	 * 
	 *  已经解开时返回 [`VaultError::AlreadyUnlocked`]：**不替换、不重复开**。
	 *  检查是 check-then-act：并发调用时两边都会算一次 KDF（约 105 ms）而只有一个成功 ——
	 *  代价照实记，不为它加一套排队逻辑。
	 */
	vaultUnlock: (passphrase: PassphraseInput) => typedError<VaultContents, VaultError>(__TAURI_INVOKE("vault_unlock", { passphrase })),
	/**
	 *  锁定：把解好的连接与口令**一起**丢掉（`Some` → `None`）。
	 * 
	 *  返回"刚才是不是真锁上了一个"：调用方（前端 / 测试）要靠它区分
	 *  "锁上了"与"本来就是锁着的"—— 后者不是错误，但也不该被报成一次状态变化。
	 * 
	 *  抹掉了什么、抹不掉什么：见模块文档的「边界」与 plan 0407 的副本清单。
	 *  口令那一页由 `memsafe` `munmap`（实测 `VmLck` 归零）；SQLCipher 内部的密钥材料
	 *  由 `cipher_memory_security` 在释放时擦零（实测：派生密钥的副本一处不剩）。
	 */
	vaultLock: () => typedError<boolean, VaultError>(__TAURI_INVOKE("vault_lock")),
	/**
	 *  库里主机池的全部行（按名字排序 —— 顺序确定，界面才不会每次刷新换一个样）。
	 * 
	 *  库锁着 → [`VaultError::Locked`]：池在库里，没有别的来路。
	 */
	vaultHosts: () => typedError<HostEntry[], VaultError>(__TAURI_INVOKE("vault_hosts")),
	/**
	 *  把一份 `~/.ssh/config`（或 `path` 指定的文件）导入 ssh 配置池。
	 * 
	 *  `path` 为 `None` → `~/.ssh/config`（家目录取不到时**明确报错**，不猜一个路径去读）。
	 *  `overwrite` = `false`（默认）：同名已存在就**不动它**，只在报告里列出来。
	 * 
	 *  支持哪些指令、不支持时是报错还是警告 —— 全在 `crate::store::sshconfig` 里，这个命令
	 *  只负责"读文件、问用户名、写库、把结果拼成报告"。
	 */
	importSshConfig: (path: string | null, overwrite: boolean) => typedError<ImportReport, ImportError>(__TAURI_INVOKE("import_ssh_config", { path, overwrite })),
	/**
	 *  库里转发规则池的全部行（按名字排序 —— 顺序确定，界面才不会每次刷新换一个样）。
	 * 
	 *  库锁着 → [`VaultError::Locked`]：规则在库里，没有别的来路。
	 */
	vaultForwards: () => typedError<ForwardEntry[], VaultError>(__TAURI_INVOKE("vault_forwards")),
	/**
	 *  库里 serial 配置池的全部行（按名字排序 —— 顺序确定，界面才不会每次刷新换一个样）。
	 * 
	 *  库锁着 → [`VaultError::Locked`]：**只有"列出来"这一步需要解锁**（池在库里）；
	 *  真正打开设备的那条命令不碰库。
	 */
	vaultSerials: () => typedError<SerialEntry[], VaultError>(__TAURI_INVOKE("vault_serials")),
	/**
	 *  本机枚举到的串口，**按路径排序**、同一路径只出现一次（顺序与去重由 `serial` 的
	 *  `normalize` 定）。
	 * 
	 *  ⚠️ **列在这里不等于打得开**（问题 #150）：Linux 那边按 udev 设备给 devnode，**不检查**它在
	 *  `/dev` 下是否存在。所以这条命令回答的是"系统认为有哪些端口"，而"能不能开"只有
	 *  [`open_serial_session`] 知道 —— 界面因此**不得**据这张表挡掉手输路径。
	 * 
	 *  空表是正常结果（本机没有串口，或者运行期拿不到 `libudev` 上下文）；只有系统调用失败才是
	 *  [`SerialIpcError::Enumerate`] —— "没有端口"与"列不出来"是两件事。
	 */
	serialPorts: () => typedError<SerialPort[], SerialIpcError>(__TAURI_INVOKE("serial_ports")),
	/**
	 *  打开一个串口会话，输出经 `channel` 以 **raw 字节**送出。
	 * 
	 *  与 [`crate::session::open_session`] 的关系：**同一条尾巴**（注册 → 频道 → 收尾线程），
	 *  差的是载体怎么来 —— 本地那条是 `PtyTransport::spawn_default()`，这条是"照这六个字段开一个设备"。
	 * 
	 *  ⚠️ 设备被拔掉时读端报错、那条流结束、会话**自己结束**（`retire` → `session_ended`）
	 *  —— 这条路径与 local / SSH 是同一条。**"原因可读"不在本条**（plan 1103）。
	 */
	openSerialSession: (channel: RawChannel, params: SerialParams) => typedError<number, SerialIpcError>(__TAURI_INVOKE("open_serial_session", { channel, params })),
	/**
	 *  打开一个终端会话，输出经 `channel` 以 **raw 字节**送出。
	 * 
	 *  返回的 id 是前端后续 `write_session` / `resize_session` / `close_session` 要用的句柄。
	 * 
	 *  会话**自己结束**时（用户在终端里敲了 `exit`、shell 崩了、PTY 被关掉）由一条收尾线程
	 *  负责：收掉它 + 发 [`SessionEnded`] 让前端关掉那个标签页。
	 */
	openSession: (channel: RawChannel) => typedError<number, IpcError>(__TAURI_INVOKE("open_session", { channel })),
	/**
	 *  打开一个 SSH 终端会话，输出经 `channel` 以 **raw 字节**送出。
	 * 
	 *  与 [`crate::session::open_session`] 的关系：**同一条尾巴**（注册 → 频道 → 收尾线程），
	 *  差的是载体怎么来 —— 本地那条是 `PtyTransport::spawn_default()`，这条是
	 *  "照池里那一行连过去"。
	 * 
	 *  ⚠️ **async**：命令体里有一次会阻塞几秒的握手（最长 `connect_timeout`），而
	 *  同步 command 跑在处理 IPC 请求的那条线程上（挡住它就等于挡住全部 IPC ——
	 *  包括用户回答问题要用的那三条命令）。
	 */
	openSshSession: (channel: RawChannel, hostId: number) => typedError<number, SshIpcError>(__TAURI_INVOKE("open_ssh_session", { channel, hostId })),
	/**  把用户输入（按键字节）送进会话。 */
	writeSession: (handle: number, data: number[]) => typedError<null, IpcError>(__TAURI_INVOKE("write_session", { handle, data })),
	/**  调整会话的窗口尺寸（列 / 行）。 */
	resizeSession: (handle: number, cols: number, rows: number) => typedError<null, IpcError>(__TAURI_INVOKE("resize_session", { handle, cols, rows })),
	/**  关闭会话：显式 kill + wait 收尸，之后这个 id 不再有效。 */
	closeSession: (handle: number) => typedError<null, IpcError>(__TAURI_INVOKE("close_session", { handle })),
	/**  回答一句秘密（口令 / 验证码 / 私钥口令）。 */
	sshPromptCredential: (id: number, secret: PassphraseInput) => typedError<null, PromptError>(__TAURI_INVOKE("ssh_prompt_credential", { id, secret })),
	/**  回答"这把没见过的主机密钥认不认"。 */
	sshPromptHostKey: (id: number, accept: boolean) => typedError<null, PromptError>(__TAURI_INVOKE("ssh_prompt_host_key", { id, accept })),
	/**
	 *  撤销这一问（用户关掉了提示面板）。**不是"接受"的另一种写法**：
	 *  它让连接以"用户取消"结束。
	 */
	sshPromptCancel: (id: number) => typedError<null, PromptError>(__TAURI_INVOKE("ssh_prompt_cancel", { id })),
	/**
	 *  打开一条隧道：读池里的规则 → **绑定本地端口** → 登记 → 建连接 → 起转发 → `已连接`。
	 * 
	 *  ⚠️ **async**：命令体里有一次会阻塞几秒的握手（最长 `connect_timeout`，跳板链再乘以
	 *  跳数）。同步命令在处理 IPC 请求的那条线程上，挡住它就等于挡住全部 IPC ——
	 *  包括用户回答问题要用的那三条（同 `open_ssh_session`）。
	 * 
	 *  顺序是刻意的（plan 0602 的第一条）：**先绑定、后连接**。端口被占用是本类功能最常见的
	 *  一类失败，用户此时还不该回答任何凭据询问 —— 拿不到端口就先报错，握手与提问都不发生。
	 * 
	 *  `Err` 只在**没登记成**时返回（库锁着 / 规则不在池里 / 方向不是 `-L` / **端口没拿到**）；
	 *  连不上属于 [`TunnelAttempt::failure`]（隧道已在册、可重试）。
	 */
	tunnelOpen: (forwardId: number) => typedError<TunnelAttempt, TunnelError>(__TAURI_INVOKE("tunnel_open", { forwardId })),
	/**
	 *  手动重试（D12：`失败 / 已停止 → 连接中`，尝试次数清零）。
	 * 
	 *  规则**重新读一遍**：端口与目标可能在上一次失败之后被改过，而重试的用户意图正是
	 *  "按现在的配置再来一次"。旧的那条转发与看护任务先收掉 —— 重试是"重来一次"，
	 *  不是"再来一条"。
	 * 
	 *  ⚠️ **只有终态能重试，而这条检查排在绑定之前**：`重连中` 也在等下一次尝试，
	 *  但那是看护任务的事（它有自己的次数与退避），用户能做的重试只在 `失败 / 已停止` 上
	 *  有意义（D12）。放在绑定之前是因为"先占一个端口再报状态不对"会在屏幕上留下一个
	 *  一闪而过的失败信息，而用户真正要看的是"现在还轮不到你重试"。
	 * 
	 *  `Err` 只在"这个句柄不是一条隧道 / 状态不是终态 / 方向不对 / 端口没拿到 / 状态推不动"
	 *  时返回；**又没连上**属于 [`TunnelAttempt::failure`]。
	 */
	tunnelRetry: (handle: number) => typedError<TunnelAttempt, TunnelError>(__TAURI_INVOKE("tunnel_retry", { handle })),
	/**
	 *  停止一条隧道（**转发 `Session` 的"关闭"就是这里**，plan 0606）：`已停止`（发事件）→
	 *  停下手上的动作（在途的一次尝试 / 看护循环）→ 回收转发（停止监听 + 断开连接）→ 从注册表摘掉。
	 * 
	 *  摘牌是**幂等**的：重复点击、或这条已经被别的路径收掉时返回 `Ok`，而不是报一个
	 *  用户没有下一步动作可做的错。
	 */
	tunnelStop: (handle: number) => typedError<null, TunnelError>(__TAURI_INVOKE("tunnel_stop", { handle })),
	/**
	 *  登记一个两栏 SFTP 会话。
	 * 
	 *  **同步命令**：它只往注册表里放一个空实体（没有任何 I/O），连接是 [`sftp_connect`] 的事。
	 *  收 `AppHandle` 只为读一次并发上限（ADR-0006 D6 的参数）—— 那个数在会话建立那一刻定下来，
	 *  之后不随配置变（配置本身只在启动时读一次）。
	 */
	sftpOpen: () => typedError<number, SftpError>(__TAURI_INVOKE("sftp_open")),
	/**
	 *  让某一侧连上本机文件系统，或者池里的那一台主机。
	 * 
	 *  目标是主机时**先试 B 档**（plan 0703）：另一栏已经连上一台不同的主机 A 的话，先建
	 *  "本机 → A → 这一台"这条链；建不起来就回退本机直连（A 档），原因记在这一侧
	 *  （[`SftpSideInfo::through_failure`]）。哪一档成不成是**这一栏连接的结果**，
	 *  于是"这次传输走的是哪一档"由端点怎么来的决定 —— 传输那个引擎一行都不用改（ADR-0006 D5）。
	 * 
	 *  ⚠️ **async**：命令体里有两次会阻塞几秒的等待（握手 + 开子系统），而同步命令跑在
	 *  处理 IPC 请求的那条线程上 —— 挡住它就等于挡住全部 IPC，包括用户回答问题要用的那三条
	 *  （同 `open_ssh_session` 的理由）。本机那一档没有等待，走同一条命令只是为了
	 *  "一栏只有一种连法"。
	 */
	sftpConnect: (handle: number, side: SftpSide, origin: SftpOrigin) => typedError<SftpSideInfo, SftpError>(__TAURI_INVOKE("sftp_connect", { handle, side, origin })),
	/**  列某一侧某个目录。 */
	sftpList: (handle: number, side: SftpSide, path: string) => typedError<SftpListing, SftpError>(__TAURI_INVOKE("sftp_list", { handle, side, path })),
	/**
	 *  把某一侧的一个文件搬到另一侧的某个路径上（plan 0702 / 0703 / 0704）。
	 * 
	 *  返回一个**编号**而不是结果：搬运是后台任务（`scope.md` §4.1 要求 progress 可见，
	 *  而一条几十秒的命令会把 IPC 堵住）。进度与结局走 [`sftp_transfers`] 与 `sftp` 探针读。
	 * 
	 *  两栏都是主机时走哪一档不在这里决定：那是**目标那一栏的端点怎么来的**（B 档 = 那条连接
	 *  是经源那一栏的主机直通来的，见 [`sftp_connect`]），这里只把结果抄进这次传输的记录
	 *  （[`SftpTransfer::via`]）。于是两档共用同一个引擎（ADR-0006 D5）。
	 * 
	 *  **并发上限在会话那一层**（plan 0704）：这条任务先在这个会话的空位上排一个队，再动端点。
	 *  排队与"用户取消 / 关会话"是可抢占的 —— 排在队里就被取消的传输**一个端点都没碰过**。
	 */
	sftpTransfer: (handle: number, from: SftpSide, fromPath: string, to: SftpSide, toPath: string) => typedError<number, SftpError>(__TAURI_INVOKE("sftp_transfer", { handle, from, fromPath, to, toPath })),
	/**
	 *  取消一次传输。
	 * 
	 *  ⚠️ 它**只推信号就返回**：临时文件是引擎那条任务删的，而"删掉了"由任务自己写进状态 ——
	 *  调用方要看的是 [`sftp_transfers`] 里那条不再是 `running`（`AGENTS.md` §7：
	 *  等真正结束，而不是猜一段时间）。
	 */
	sftpTransferCancel: (handle: number, id: number) => typedError<null, SftpError>(__TAURI_INVOKE("sftp_transfer_cancel", { handle, id })),
	/**  这个会话发起过的传输（新的在前）。 */
	sftpTransfers: (handle: number) => typedError<SftpTransfer[], SftpError>(__TAURI_INVOKE("sftp_transfers", { handle })),
	/**  两侧的状态（只读命令用）。 */
	sftpSides: (handle: number) => typedError<SftpSideInfo[], SftpError>(__TAURI_INVOKE("sftp_sides", { handle })),
	/**
	 *  列出后端已经登记的全部 SFTP 会话。
	 * 
	 *  ⚠️ 它存在的理由是一条产品纪律：**关面板不等于结束会话**（`scope.md` §5.6 ——
	 *  文件传输是仅渲染的视图）。面板必须能找回那个会话，否则"关前端不影响后端执行"
	 *  就变成了"关前端等于失控"：会话还在，而没有任何地方能再操作它。
	 */
	sftpSessions: () => typedError<SftpSummary[], SftpError>(__TAURI_INVOKE("sftp_sessions")),
	/**
	 *  关掉一个 SFTP 会话：两侧连接断开，会话从注册表摘掉。
	 * 
	 *  ⚠️ **它是这个会话唯一的关闭入口**：面板是仅渲染的视图（`scope.md` §5.6），
	 *  关面板不停后端会话 —— 停止是这里这个显式动作（与隧道那边 `tunnel_stop` 同一条纪律）。
	 *  幂等：已经关过的句柄返回 `Ok`（不是失败）。
	 * 
	 *  ⚠️ **顺序不能换**：先推中止、**等清理落地**，再断连接。临时文件是用那条连接删掉的，
	 *  反过来做的话 `scope.md` §4.2 那一格（"关闭 `Session` → 删除临时文件"）永远做不到。
	 *  等一下的上界是 SFTP 自己的请求期限（一次读或写、加上一次删除）—— 不会无限等。
	 */
	sftpClose: (handle: number) => typedError<null, SftpError>(__TAURI_INVOKE("sftp_close", { handle })),
	/**  读一次 CLI 与状态（面板打开时用）。 */
	bwCliStatus: () => __TAURI_INVOKE<BwSnapshot>("bw_cli_status"),
	/**  换两个轴。**只改选择并记下来**，不下载（下载是 [`bw_cli_install`]）。 */
	bwCliSettings: (binary: string, appdata: string) => typedError<BwSnapshot, BwIpcError>(__TAURI_INVOKE("bw_cli_settings", { binary, appdata })),
	/**
	 *  下载一份 OSS 变体并**改用它**（下载是用户动作，ADR-0007 D2）。
	 * 
	 *  ⚠️ **async 且把阻塞那一半放进阻塞池**：下载约 45 MB，同步命令会把处理 IPC 的那条线程
	 *  占住（同 `open_ssh_session` 的理由）。下载**不持锁** —— 它只写数据目录下的版本目录，
	 *  不碰 CLI 的状态文件，所以这期间面板还能读状态。
	 */
	bwCliInstall: () => typedError<BwSnapshot, BwIpcError>(__TAURI_INVOKE("bw_cli_install")),
	/**
	 *  读一次三态（界面刷新用）。
	 * 
	 *  **不返回 `Err`**：读不出来是快照里的一个字段（`problem`），而不是一次调用失败 ——
	 *  界面要显示的是"为什么读不出来"那句话，而不是一个被抛出的错误。
	 */
	bwStatus: () => __TAURI_INVOKE<BwSnapshot>("bw_status"),
	/**  设服务器地址（自托管）。官方云的默认值**不写** `config`：`bw` 自己的默认就是它。 */
	bwServerSet: (url: string) => typedError<BwSnapshot, BwIpcError>(__TAURI_INVOKE("bw_server_set", { url })),
	/**  登录（邮箱 + 主密码；两步验证可选）。成功时 session key 进内存。 */
	bwLogin: (email: string, password: PassphraseInput, method: string | null, code: string | null) => typedError<BwSnapshot, BwIpcError>(__TAURI_INVOKE("bw_login", { email, password, method, code })),
	/**  解锁。成功时**换掉**手上的 session key（旧的在 CLI 那一侧已经失效）。 */
	bwUnlock: (password: PassphraseInput) => typedError<BwSnapshot, BwIpcError>(__TAURI_INVOKE("bw_unlock", { password })),
	/**  锁定：让 CLI 那一侧的 key 失效，并抹掉手上的那一份。 */
	bwLock: () => typedError<BwSnapshot, BwIpcError>(__TAURI_INVOKE("bw_lock")),
	/**  登出：连登录态一起清掉。 */
	bwLogout: () => typedError<BwSnapshot, BwIpcError>(__TAURI_INVOKE("bw_logout")),
	/**  与上游对齐（纯 pull）。需要 session key。 */
	bwSync: () => typedError<BwSnapshot, BwIpcError>(__TAURI_INVOKE("bw_sync")),
	/**
	 *  把 Bitwarden 里的 SSH key 条目**只读导入**本地密钥池（plan 0903）。
	 * 
	 *  两把锁**不同时持有**：先在 `bw` 那把锁里跑完 `list items` 并解析成我们自己的类型，
	 *  放锁之后才去动库。顺序反过来（持库锁去起进程）会让一次 `bw` 调用把整个库锁住几百毫秒。
	 * 
	 *  这一条**不返回快照**：导入不改三态，也不改两个轴 —— 面板上要刷新的东西由调用方自己再读一次。
	 */
	bwImportKeys: (overwrite: boolean) => typedError<BwImportReport, BwImportError>(__TAURI_INVOKE("bw_import_keys", { overwrite })),
	/**
	 *  **离线**自检：库里那份私钥还配得上导入时记下的指纹吗（plan 0904）。
	 * 
	 *  起进程数为 **0**、联网 **0**：所以断网时它照样能用 —— 这正是 `fingerprint` 那条路
	 *  存在的理由（`revisionDate` 那条必须联网）。
	 * 
	 *  需要库解锁（要读私钥），**不需要** session。逐行报，一行坏了不影响其余行。
	 */
	bwCacheVerify: () => typedError<BwCacheReport, BwImportError>(__TAURI_INVOKE("bw_cache_verify")),
	/**
	 *  **联网**比对：上游那几条的 `revisionDate` 与缓存里的还一样吗（plan 0904）。
	 * 
	 *  **只报不改**：刷新是用户再点一次导入（`overwrite`）。自动刷新会把一次网络往返变成
	 *  一次对库的写入，而那条路径上没有任何人看着。
	 */
	bwCacheCheck: () => typedError<BwRefreshReport, BwImportError>(__TAURI_INVOKE("bw_cache_check")),
};

/** Events */
export const events = {
	sessionEnded: makeEvent<SessionEnded>("session_ended"),
	sshPrompt: makeEvent<PromptRequest>("ssh_prompt"),
	sshPromptDismissed: makeEvent<PromptDismissed>("ssh_prompt_dismissed"),
	tunnelState: makeEvent<TunnelStateChanged>("tunnel_state"),
};

/* Types */
/**
 *  认证方式过 IPC 的形状。
 * 
 *  与 `crate::store::pools::hosts::Auth` 分开：存储 crate **不依赖 specta**
 *  （那是 app 钉住版本的东西），所以这里做一次显式映射 —— 而映射写成穷尽 `match`，
 *  池里加一种认证方式时**这里编译不过**。
 */
export type AuthMethod = "password" | "publicKey" | "agent";

/**  一条缓存的校验结果。 */
export type BwCacheEntry = {
	name: string,
	cipherId: string,
	/**  导入时记下的上游指纹（参照物）。 */
	recordedFingerprint: string,
	/**  从库里这把私钥**算出来的**指纹；读不出来时是 `null`。 */
	computedFingerprint: string | null,
	verdict: BwCacheVerdict,
};

/**  缓存自检的一份读数（**不联网、不起 `bw`**）。 */
export type BwCacheReport = {
	/**  库里有多少条来历行（= 有多少把钥匙被这一层看着）。 */
	checked: number,
	entries: BwCacheEntry[],
};

/**  三档，对应三个不同的下一步动作。 */
export type BwCacheVerdict = 
/**  算出来的与记下的**逐字符相同**：这份缓存完好。 */
"match" | 
/**
 *  对不上：库里的私钥**不是**当初导入的那一把（或被改过）。这一条要用户自己判断 ——
 *  也可能是他有意换的，所以命令只报，不动任何东西。
 */
"mismatch" | 
/**  私钥读不出来 / 解析不了（带口令的私钥也算）。`detail` 里有原因。 */
"unreadable";

/**  CLI 那一块：这两个轴解析出来是什么。 */
export type BwCliInfo = {
	/**  `host` / `managed`。 */
	binary: string,
	/**  `host` / `managed`。 */
	appdata: string,
	/**  解析到的可执行文件（解析不出来时为空）。 */
	program: string | null,
	version: string | null,
	/**  `oss` / `proprietary` / `unknown`。 */
	variant: string | null,
	/**  需要提示许可证时的那句话（只有专有变体有）。 */
	licenseNotice: string | null,
	/**  解析不出来时的原因。**"没有 `bw`"与"还没下载"是不同的两句**（ADR-0007 D5）。 */
	problem: string | null,
};

/**
 *  与 [`crate::bw::BwError`] 一一对应。分成两份是因为 IPC 上要的是一个能穷尽 `switch`
 *  的枚举，而 crate 的错误带着内部细节（路径、长度、被拒绝的地址）。
 */
export type BwErrorKind = 
/**  `PATH` 里没有 `bw`（`host` 那一轴）。 */
"missingBinary" | 
/**  还没下载过（`managed` 那一轴）。 */
"notInstalled" | "notRunnable" | "unsupportedTarget" | "noRelease" | "network" | "tls" | "insecureUrl" | "invalidServer" | 
/**  `bw` 说没有登录 —— 界面上该做的是"先登录"。 */
"notLoggedIn" | 
/**  `bw` 说这个 vault 锁着 —— 界面上该做的是"先解锁"（与上一条不同的一句话）。 */
"locked" | 
/**  `bw` 以非 0 退出而我们认不出类别（原话在 `message` 里）。 */
"commandFailed" | "parse" | "archive" | "io" | "timeout" | "protectedPage" | "internal";

/**  导入 SSH key 失败。变体按**用户的下一步动作**分（与 `ImportError` 同一原则）。 */
export type BwImportError = 
/**  库没解锁。导入要**写**进密钥池，所以解锁是硬前提（不像读快照那样只是读不到）。 */
{ kind: "locked" } | 
/**  `bw` 那一侧的失败。`kind` 与面板其余部分同一个域（前端按它分辨，不匹配消息字符串）。 */
{ kind: "bw"; detail: {
	kind: BwErrorKind,
	message: string,
} } | 
/**  其余（数据目录未定、写库失败……）。 */
{ kind: "failed"; detail: {
	message: string,
} };

/**
 *  导入报告（过 IPC 的形状）。
 * 
 *  它要回答三个问题，缺一个用户就没法相信这次导入 —— 与 `import_ssh_config` 的
 *  [`crate::store::ipc::pools::ImportReport`] 同一形状：
 * 
 *  | 字段 | 回答 |
 *  |---|---|
 *  | [`Self::seen`] / [`Self::ssh_keys`] | **上游那边看到了什么**（全部条目数 / 其中 SSH key 数） |
 *  | [`Self::created`] / [`Self::replaced`] | **池里变了吗** |
 *  | [`Self::skipped`] | **哪几条没进来、为什么**（逐条给下一步动作） |
 */
export type BwImportReport = {
	/**  上游一共给了多少条（**全部类型**）。 */
	seen: number,
	/**  其中 `type = 5`（SSH key）的。 */
	sshKeys: number,
	created: ImportedKey[],
	replaced: ImportedKey[],
	skipped: SkippedKey[],
	/**  我们替用户补上的说明（目前只有一条：钥匙怎么才会接到主机上）。 */
	notes: string[],
};

/**  没动这一条的原因。**每个取值对应一个不同的下一步动作**。 */
export type BwImportSkip = 
/**  池里已经有同名的行了。 */
"exists" | 
/**  **这一批里**已经有同名的了（上游允许两个条目同名）。 */
"duplicateName" | 
/**  池里那一行已经归**另外一条**上游条目了。 */
"claimed" | 
/**  这一条只有公钥（上游允许），没有私钥可导。 */
"noPrivateKey" | 
/**  缺 id / 名字 / `revisionDate`：导进来会成为一条以后认不出来的记录。 */
"noProvenance" | 
/**  私钥超过受保护页（16 KiB），进不了库 —— 与 `keys::PrivateKey::new` 同一条上限。 */
"tooLong";

/**  失败的形状。**界面按 `kind` 分辨**，不匹配消息字符串（同 `SshIpcError` 的口径）。 */
export type BwIpcError = {
	kind: BwErrorKind,
	/**  `bw` 自己说的那句话（或我们的可读原因）。**只用来显示**。 */
	message: string,
};

/**  一条缓存与上游的比对结果。 */
export type BwRefreshEntry = {
	name: string,
	cipherId: string,
	state: BwRefreshState,
};

/**  上游比对的一份读数（**要 session**：它起一次 `bw list items --raw`）。 */
export type BwRefreshReport = {
	/**  上游一共给了多少条（全部类型）。 */
	seen: number,
	entries: BwRefreshEntry[],
	/**  **上游有、缓存里没有**的 SSH key 条目名（"该导入一次"的提示）。 */
	newUpstream: string[],
};

/**
 *  三档。⚠️ `Changed` **不由 `fingerprint` 判**（那是"本地这份还好吗"）：上游的
 *  `revisionDate` 才是"有没有变过"的判据（`docs/bitwarden.md` §5）。
 */
export type BwRefreshState = "upToDate" | "changed" | 
/**  上游已经看不到这一条了（被删或被移走）——"再导一次"救不了它。 */
"gone";

/**  一次命令之后的完整读数（也是 `bitwarden` probe 报的东西）。 */
export type BwSnapshot = {
	cli: BwCliInfo,
	/**  CLI 里当前配置的服务器（`bw config server` 的回读）—— 登录之前也读得到。 */
	server: string | null,
	/**  CLI 说得出来的状态；`bw` 自己跑不起来时为 `None`。 */
	status: BwVaultStatus | null,
	/**  **我们手里有没有 session key**（不是 key 本身）。 */
	hasSession: boolean,
	/**  读状态失败的原因。 */
	problem: string | null,
};

/**  三态的投影。取值与 `bw status --raw` 一致（`unauthenticated` / `locked` / `unlocked`）。 */
export type BwVaultStatus = {
	serverUrl: string | null,
	lastSync: string | null,
	userEmail: string | null,
	userId: string | null,
	state: string,
};

/**  报告里的一条：行号 + 关键字 + 说法。 */
export type ConfigFinding = {
	line: number,
	keyword: string,
	message: string,
};

/**  转发方向过 IPC 的形状（与 [`AuthMethod`] 同一个理由：存储 crate 不依赖 specta）。 */
export type ForwardDirection = 
/**  `-L`：本地绑定，转发到目标。 */
"local" | 
/**  `-R`：远端绑定，转发回本地侧。 */
"remote" | 
/**  `-D`：本地起一个 SOCKS5，目标由客户端给。 */
"dynamic";

/**
 *  界面看得见的一条转发规则。
 * 
 *  `target_host` / `target_port` 是 `Option`：`dynamic`（SOCKS5）**没有目标** ——
 *  那是库里 `CHECK` 拦着的不变量，这里如实照搬，而不是填一个看起来像真的空串。
 */
export type ForwardEntry = {
	/**  池里的行 id（`tunnel_open` 要的就是它）。 */
	id: number,
	name: string,
	direction: ForwardDirection,
	bindHost: string,
	bindPort: number,
	targetHost: string | null,
	targetPort: number | null,
	/**  这条规则属于哪台主机（`hosts.id`）—— 隧道**连的就是它**。 */
	hostId: number,
	/**  会话建立时是否自动起这条转发（plan 0601 只读取，不据此自动开）。 */
	autostart: boolean,
};

/**  界面看得见的一台主机。 */
export type HostEntry = {
	/**  池里的行 id（`open_ssh_session` 要的就是它）。 */
	id: number,
	/**  用户给这台主机起的名字（池里唯一）。标签页标题用它。 */
	name: string,
	/**  主机名或 IP。 */
	host: string,
	port: number,
	user: string,
	/**  认证方式（池里的取值，见 [`AuthMethod`]）。 */
	auth: AuthMethod,
	/**
	 *  配了哪把钥匙（`keys.id`）。只有 `publickey` 时可能非空 —— 而它也可能是空的
	 *  （走 ssh-agent 的钥匙不在我们的池里）。
	 */
	keyId: number | null,
	/**
	 *  这台主机**经哪台连**（`hosts.jump_id`，plan 0505）。
	 * 
	 *  出现在这里是因为它已经是库里的一列，而"从界面选主机"的人有权知道这一次点下去
	 *  会**经过谁** —— 不然一条跳板链在界面上没有任何痕迹，连不上时也无从判断是目标的问题
	 *  还是跳板的问题。链本身（跳板还有跳板）由连接那条路自己走，界面只看一跳。
	 */
	jumpId: number | null,
};

/**  导入失败。变体按**用户的下一步动作**分（与 `VaultError` / `SshIpcError` 同一原则）。 */
export type ImportError = 
/**  库没解锁。导入要**写**进 ssh 配置池，所以解锁是硬前提（不像列主机那样只是读不到）。 */
{ kind: "locked" } | 
/**
 *  文件读不到（不存在 / 权限 / 不是 UTF-8）。**不是"导入了 0 台"**：这两件事要分得开，
 *  否则用户会去池子里找一台本来就还在原地的机器。
 */
{ kind: "unreadable"; detail: {
	path: string,
	message: string,
} } | 
/**
 *  这份配置**整份**不能照着做（`Match` / `Include` / 不认识的指令……）。
 *  一行都没写 —— 这是"宁可明确报错，也不静默误解析"那条判据的落点。
 * 
 *  `message` 里带条数（`thiserror` 的格式串只认字段，所以那句话在命令里拼好）。
 */
{ kind: "refused"; detail: {
	path: string,
	message: string,
	problems: ConfigFinding[],
} } | 
/**  其余（写库失败、取不到本机用户名……）。 */
{ kind: "failed"; detail: {
	message: string,
} };

/**
 *  导入报告（过 IPC 的形状）。
 * 
 *  它同时回答三个问题，缺一个用户就没法相信这次导入：
 * 
 *  | 字段 | 回答 |
 *  |---|---|
 *  | [`Self::created`] / [`Self::updated`] / [`Self::skipped`] | **池里变了吗** |
 *  | [`Self::ignored`] | **配置里哪些话我们没照做**（受限子集的边界就落在这里） |
 *  | [`Self::notes`] | **我们替你补了什么、跳过了什么**（通配块、补建的跳板条目……） |
 */
export type ImportReport = {
	/**  **真读的那个文件**（`path` 没给时是这样推出来的）。 */
	path: string,
	created: ImportedHost[],
	updated: ImportedHost[],
	skipped: SkippedHost[],
	/**  没生效的指令：行号 + 关键字 + 说法。 */
	ignored: ConfigFinding[],
	notes: string[],
};

/**  池里新增 / 被替换的一行。 */
export type ImportedHost = {
	id: number,
	name: string,
};

/**
 *  池里新增 / 被替换的一把钥匙。
 * 
 *  **不带行 id**：报告要回答的是"哪一把钥匙进来了"，而名字是池里的 `UNIQUE` 列；
 *  行 id 是 `i64`，过 IPC 要另一套 checked 转换（同 `HostId` 的理由）—— 这里不需要它。
 */
export type ImportedKey = {
	name: string,
	/**  上游报的那串 `SHA256:…`（plan 0904 的离线自检拿它当参照）。 */
	fingerprint: string,
};

/**
 *  IPC 边界的错误。
 * 
 *  域边界就在这里：`session` 的模型与 `pty` **都不知道 IPC 存在**，所以它们的错误
 *  在这里收敛成一个可序列化的形状（`AGENTS.md` §3.4）。前端能据此区分的只有四件事：
 *  会话不存在 / 载体出错 / 频道句柄无效 / 隧道状态转移被拒 —— 再细的分支要等真有 UI
 *  依赖它时再加。
 */
export type IpcError = 
/**  这个会话不存在：已经关闭，或从来没打开过。**两者的处置相同**，故不区分。 */
{ kind: "notFound"; detail: {
	handle: number,
} } | 
/**  载体失败（IO / 能力不支持 / 已关闭）。消息原样来自 `TransportError`。 */
{ kind: "transport"; detail: {
	message: string,
} } | 
/**  传给后端的东西不是合法的频道句柄。 */
{ kind: "channel"; detail: {
	message: string,
} } | 
/**
 *  隧道的状态转移被拒（plan 0601）。**不是内部故障**：最常见的就是"另一条路已经
 *  把它推到终态了"（重试与停止几乎同时发生），前端刷新一下即可。
 */
{ kind: "tunnel"; detail: {
	message: string,
} } | 
/**
 *  内部状态不可用（Mutex 中毒，或 core 的 id 装不进句柄）。
 *  **不是用户错误** —— 但也不能 `unwrap`。
 */
{ kind: "internal"; detail: {
	message: string,
} };

/**
 *  口令 / 凭据**经 IPC 进来的形态**（`PassphraseInput`）。
 * 
 *  它是"一句秘密从前端进来"在 IPC 边界上的唯一类型 —— 库解锁（plan 0407）与 SSH 的凭据
 *  提问（plan 0504）共用它。共用而不是各写一个，是因为它的性质正是两者都要的：
 *  它唯一能做的事是 [`PassphraseInput::into_bytes`]。
 * 
 *  刻意**没有** `Debug`：`tracing::info!(?input)` 是**编译错误**，而不是"打码" ——
 *  与 `Passphrase` 同一手法（`AGENTS.md` §3.4）。
 * 
 *  `#[specta(transparent)]` 让它生成成 `string`（线上确实是 JSON 字符串），
 *  前端因此不需要为它手写第二份签名（对比 `RawChannel` 那段：那个需要手写，
 *  因为频道句柄的语义生成器表达不出来）。
 */
export type PassphraseInput = string;

/**
 *  这次提问**不用答了**（超时被撤下）。
 * 
 *  为什么要有它：界面上一份提示不能永远留着 —— 没有人答的那一问在
 *  [`PROMPT_TIMEOUT`] 之后会被撤掉，前端必须**看得见**这件事，否则它会一直显示一个
 *  早已不存在的提问（用户再点"确定"只会得到 `Gone`）。
 */
export type PromptDismissed = {
	id: number,
};

/**
 *  回答提问时可能出的错。
 * 
 *  变体按**前端能做什么**分：`Gone` 什么都不用做（那一问已经超时了，界面自己也收到了
 *  `ssh_prompt_dismissed`），`Invalid` 要用户改一下再提交，`Internal` 只该记日志。
 */
export type PromptError = 
/**  这个编号没有在等的提问：已经超时被撤下，或者已经答过了。 */
{ kind: "gone"; detail: {
	id: number,
} } | 
/**  答案本身不合法（空 / 比一页受保护内存还长）。**不是截断**。 */
{ kind: "invalid"; detail: {
	message: string,
} } | 
/**  内部状态不可用（待答表中毒）。 */
{ kind: "internal"; detail: {
	message: string,
} };

/**
 *  后端要问用户一件事。前端据此打开提示界面。
 * 
 *  两个变体放在同一个事件里，是因为它们**在同一条路上**发生（连接中途、同一个往返机制、
 *  同一个超时）—— 分成两个事件只会让"谁在问"多一份要维护的契约。
 *  ⚠️ 但**策略**完全不同：主机密钥那一问只有"接受 / 拒绝"两个答案（见 `ssh.rs` 的接线），
 *  凭据那一问是一句秘密。
 */
export type PromptRequest = 
/**  一把没见过的服务端主机密钥，请用户核对指纹（ADR-0003 D11）。 */
{ kind: "hostKey"; id: number; host: string; port: number; 
/**  密钥算法（`ssh-ed25519` 一类）—— 与指纹一起显示，用户核对的是指纹。 */
algorithm: string; 
/**  `SHA256:…`，**要用户拿去核对的那串东西**。 */
fingerprint: string } | 
/**  要一句秘密。 */
{ kind: "credential"; id: number; 
/**  `user@host:port`（`SshTarget` 的 `Display`）—— 用户得知道在给谁输口令。 */
target: string; credential: SecretKind; 
/**  直接可以显示给用户的一句话（`CredentialRequest::prompt`）。 */
prompt: string };

/**
 *  前端 raw 字节频道的句柄。
 * 
 *  **线上就是一个字符串**（`__CHANNEL__:<id>`）：tauri 的频道是前端创建、只把 id 递给
 *  后端的东西。所以这里声明成"字符串"而不是 `Channel<Vec<u8>>` —— 后者在 JS 侧是
 *  `number[]`（JSON 数组），是本文件开头说的那条慢路。
 * 
 *  校验在 Rust 侧：解析不出 `<id>` 就报 `IpcError::Channel`，不会静默丢掉输出。
 */
export type RawChannel = string;

/**
 *  **要哪一种凭据** —— 过 IPC 的形态（`ssh` 的 `CredentialKind` 没有 `specta`）。
 * 
 *  前端用它决定提示语的语气（验证码 / 口令 / 私钥口令），**不决定行为**：
 *  三种都是"一句秘密"，答案的走法完全相同。
 */
export type SecretKind = "loginPassword" | "keyboardInteractive" | "keyPassphrase";

/**
 *  界面看得见的一条串口配置。
 * 
 *  `data_bits` / `stop_bits` 保持**库里的原始数值**（`5..=8` / `1..=2`）：取值范围由库的
 *  `CHECK` 与 `TryFrom` 两头夹着，而这一层多做一个枚举只会让"越界取值"多一个说不清来路的地方。
 */
export type SerialEntry = {
	/**  池里的行 id。 */
	id: number,
	/**  用户给这条配置起的名字（池里唯一）。标签页标题用它。 */
	name: string,
	/**  设备路径（`/dev/ttyUSB0` / `COM3`）。 */
	port: string,
	baud: number,
	dataBits: number,
	stopBits: number,
	parity: SerialParity,
	flow: SerialFlow,
};

/**  流控过 IPC 的形状。理由同 [`SerialParity`]。 */
export type SerialFlow = "none" | "software" | "hardware";

/**  IPC 边界的串口错误。变体按**用户的下一步动作**分（同 `VaultError` / `SshIpcError` 的原则）。 */
export type SerialIpcError = 
/**
 *  参数不合法。报的是**字段与取值** —— 用户要改的是那一个字段（池行里那一格，
 *  或者 plan 1102 的表单上那一栏）。
 */
{ kind: "settings"; detail: {
	field: string,
	value: string,
} } | 
/**
 *  打开这个设备失败。**路径在这里**，因为用户要去看的是那个设备、不是我们代码里的哪一行
 *  （与 `serial` 的 `SerialError::Open` / `Handle` 同一条口径）。
 */
{ kind: "open"; detail: {
	path: string,
	message: string,
} } | 
/**
 *  列不出本机端口（系统调用失败）。**用户的下一步动作是手输一条路径** ——
 *  界面在这一档旁边留着那条输入即可，不该把它读成"本机没有串口"
 *  （空表才是那个意思，见 [`serial_ports`]）。
 */
{ kind: "enumerate"; detail: {
	message: string,
} } | 
/**  内部状态不可用（会话表中毒、收尾线程起不来、频道句柄无效）。 */
{ kind: "internal"; detail: {
	message: string,
} };

/**
 *  开一个串口会话要的**全部参数**（过 IPC 的形态）。
 * 
 *  为什么是一个结构体而不是六个平铺参数：一来六个参数加 `app` / `webview` / `channel`
 *  会越过 clippy 的上限，二来它本来就是**一个概念**（"用这套参数开一个设备"）——
 *  生成物里因此只有一项，前端把池行原样填进来即可。
 */
export type SerialParams = {
	/**  设备路径（`/dev/ttyUSB0` / `COM3`）。 */
	port: string,
	baud: number,
	dataBits: number,
	stopBits: number,
	parity: SerialParity,
	flow: SerialFlow,
};

/**
 *  校验位过 IPC 的形状。
 * 
 *  与 `crate::store::pools::serial::Parity` 分开：存储 crate **不依赖 specta**
 *  （那是 app 钉住版本的东西），串口 crate 也**不带 serde**。两侧的映射都写成穷尽 `match`，
 *  于是任一侧加一种取值时**这里编译不过** —— 而不是悄悄少一个分支。
 */
export type SerialParity = "none" | "even" | "odd";

/**  一条端口的**过 IPC 表示**。 */
export type SerialPort = {
	/**  设备路径（Unix 上是 `/dev/ttyUSB0` 一类，Windows 上是 `COM3`）。 */
	path: string,
	/**  这条路径由什么硬件暴露。 */
	kind: SerialPortKind,
};

/**
 *  端口的硬件类别过 IPC 的形状。理由同 [`SerialParity`]：`serial` 不带 serde / specta，
 *  两侧各认自己的类型，映射写成穷尽 `match`。
 * 
 *  `Usb` 的五项与 `Windows` 的两项**都可能缺**（设备自己没报、udev 的硬件库也没有、
 *  注册表里那个值不存在）：缺了就是 `None`，不填假值（`AGENTS.md` §3.4 的"字段值不得虚构"）。
 * 
 *  ⚠️ `Windows` 这一档**只在 Windows 上产生**（plan 0803）：取值只来自那边的注册表。
 *  其余平台上它也还在类型里 —— 前端因此只有一套形状，不必按平台分支。
 */
export type SerialPortKind = 
/**  USB 转串口。 */
({ usb: {
	/**  厂商号。 */
	vid: number,
	/**  产品号。 */
	pid: number,
	/**  设备自报的序列号。 */
	serial: string | null,
	/**  厂商名。 */
	manufacturer: string | null,
	/**  产品名。 */
	product: string | null,
} }) & { windows?: never } | 
/**  主板上的 PCI 串口。 */
"pci" | 
/**  蓝牙串口（`rfcomm`）。 */
"bluetooth" | 
/**
 *  **Windows 专有的一档**：注册表的 PnP 设备项给出的描述（plan 0803）。
 * 
 *  上游在 Windows 上把一切都报成 `Unknown`（见 `serial::enumerate` 的模块文档），
 *  所以那边的端口只有走这一档才带得出描述。两项都可能缺。
 */
({ windows: {
	/**
	 *  设备描述（例如 `USB-SERIAL CH340 (COM3)`）。
	 * 
	 *  ⚠️ **必须逐字段写 `rename`**：枚举上的 `rename_all` 只改**变体名**，
	 *  不改结构体变体里的字段名（与 `SerialEntry` 那种普通结构体不同）。
	 *  漏掉它，生成物里就是 `friendly_name`，而前端读的是 `friendlyName` ——
	 *  类型都对得上，界面上却一直显示不出来。
	 */
	friendlyName: string | null,
	/**  硬件 id（例如 `USB\\VID_1A86&PID_7523`）。 */
	hardwareId: string | null,
} }) & { usb?: never } | 
/**  判定不出来。 */
"unknown";

/**
 *  一个会话**自己**结束了：载体（PTY 里的 shell）退出 —— 用户敲了 `exit`、shell 崩了、
 *  PTY 被关掉。总之**不是**"用户关掉了标签页"那条路。
 * 
 *  前端据此关掉对应的标签页：标签页与会话**同生命期**（`docs/scope.md` §5.6），两个方向都要
 *  成立 —— 关标签页 → 丢弃会话（plan 0305）；会话自己走 → 标签页跟着走（本步）。
 */
export type SessionEnded = {
	/**  哪个会话结束了。前端按它找要关掉的那个标签页。 */
	handle: number,
	/**
	 *  这次结束的**可读描述**：载体有结局就报结局（"退出码 0" / "被信号 … 终止"），
	 *  没有结局的载体（串口）报的是它输出流断掉的原因（"串口设备已断开：…"）。
	 *  `None` = 既没有结局也没有原因（收尾时出了岔子 —— 见 `retire`）。
	 * 
	 *  两种都进同一个字段是刻意的：界面要说的是"这条会话怎么结束的"，那是**一句话**，
	 *  分成两个字段只会让调用方去猜该显示哪一个。
	 */
	status: string | null,
};

/**  一条目录条目。 */
export type SftpEntry = {
	name: string,
	kind: SftpEntryKind,
};

/**  一条目录条目的类型（过 IPC 的稳定短名）。 */
export type SftpEntryKind = "file" | "directory" | "symlink" | "other";

/**  IPC 边界的 SFTP 错误。变体按**用户的下一步动作**分（同 `VaultError` / `SshIpcError`）。 */
export type SftpError = 
/**  库没解锁。主机在库里，**没有别的来路**。 */
{ kind: "locked" } | 
/**  池里没有这台主机。 */
{ kind: "noSuchHost"; detail: {
	id: number,
} } | 
/**  这个句柄不是一个 SFTP 会话（已经关闭 / 从来不存在）。 */
{ kind: "notAnSftp"; detail: {
	handle: number,
} } | 
/**  这一侧还没有连接。**与失败分开**：那是"连过但没连上"，这是"还没连"。 */
{ kind: "notConnected"; detail: {
	side: string,
} } | 
/**  没有这个编号的传输（已经结束并从表里清掉了，或者编号本来就错）。 */
{ kind: "noSuchTransfer"; detail: {
	id: number,
} } | 
/**  连接这条路失败。`kind` 是给界面分辨**警报**用的（同 `SshIpcError`）。 */
{ kind: "failed"; detail: {
	kind: SshFailureKind,
	message: string,
} } | 
/**  内部状态不可用。 */
{ kind: "internal"; detail: {
	message: string,
} };

/**
 *  并发上限的三个读数（plan 0704）。
 * 
 *  它们一起答一个问题："上限真的在起作用吗" —— `live` 是此刻在搬的文件数，`peak` 是这个
 *  会话见过的最多同时几个（**会话生命期内**，不回落）。⚠️ 排队中的传输在
 *  [`SftpTransfer`] 里与"正在搬"长得一样（状态枚举只有"还没结束"这一档），
 *  分辨它们靠 `live` 比"还没结束的条数"少。
 */
export type SftpInFlight = {
	/**  上限（来自配置，见 `crate::config::Transfer::in_flight`）。 */
	limit: number,
	/**  此刻有几个文件在搬。 */
	live: number,
	/**  这个会话见过的最多同时几个。 */
	peak: number,
};

/**
 *  一次列目录的结果。
 * 
 *  `path` 是**端点规范化之后**的路径（远端是 `realpath`，本机是 `canonicalize`）：
 *  前端拿它当"当前目录"，于是"返回上一级"不必在前端拼字符串。
 */
export type SftpListing = {
	path: string,
	entries: SftpEntry[],
};

/**
 *  一侧连的**是什么**：本机文件系统，还是池里的一台主机（plan 0702）。
 * 
 *  `侧` 与 `源` 的关系是"这一栏此刻对着哪一边"，而传输的两个方向都是**侧到侧** ——
 *  于是"本机 ↔ 主机"与将来的"主机 ↔ 主机"（plan 0703）在契约上是同一个形状。
 */
export type SftpOrigin = 
/**  本机文件系统。没有连接、没有认证、没有失败档 —— 连上就是"这一栏可以用了"。 */
{ kind: "local" } | 
/**  池里的一台主机。 */
{ kind: "host"; id: number };

/**  两栏里的哪一栏。**唯一进入契约的呈现概念**（ADR-0006 D7）。 */
export type SftpSide = "left" | "right";

/**  一侧的**过 IPC 表示**。 */
export type SftpSideInfo = {
	side: SftpSide,
	/**  这一栏连的是什么（还没选就是 `None`）。 */
	origin: SftpOrigin | null,
	/**  那一台的名字（界面上那一栏的标题；还没选就是空串）。 */
	name: string,
	state: SftpSideState,
	/**
	 *  上一次失败的原因（`state = failed` 时才有）。**字段值不虚构**：
	 *  没有失败就不写它（`None`），不填一句 "unknown"（`docs/logging.md` 的口径）。
	 */
	failure: string | null,
	/**  当前目录（连上之后才有）。 */
	path: string | null,
	/**
	 *  这一侧的连接是**经哪台直通**到达的（plan 0703 的 B 档）。`None` = 本机直接连过去。
	 * 
	 *  **字段值不虚构**：不是直通就不写它，不填一个"0"或空串顶替（`docs/logging.md` 的口径）。
	 */
	through: number | null,
	/**
	 *  试过直通、没成时那条链的失败原因（改了直连并成功的证据）。
	 * 
	 *  与 [`Self::failure`] 分开：那是"这一栏连不上"，这是"原本想走的那条路没走成"。
	 *  两者同时为空是常态；两条都不成时**两个都会有**（各说各的那一次尝试）。
	 */
	throughFailure: string | null,
};

/**
 *  一侧的连接状态。
 * 
 *  只有四个取值，而且**没有**"重连中"：SFTP 没有重连循环（那是隧道的事，ADR-0003 D13）。
 *  一次连接失败就停在 `失败`，重试是用户的动作（再点一次「连接」）。
 */
export type SftpSideState = 
/**  还没连（初始状态），或者连过之后被断开。 */
"disconnected" | 
/**  正在建连接 / 认证 / 开 sftp 子系统。 */
"connecting" | 
/**  会话可用。 */
"connected" | 
/**  上一次尝试失败（原因在 [`SftpSideInfo::failure`]）。 */
"failed";

/**  一个 SFTP 会话的**过 IPC 表示**（只读命令与探针共用）。 */
export type SftpSummary = {
	handle: number,
	/**  两侧，**永远两项**且顺序固定（`left` 在前）—— 前端因此不必处理"缺了一侧"。 */
	sides: SftpSideInfo[],
	/**  这个会话发起过的传输，**新的在前**。 */
	transfers: SftpTransfer[],
	/**  这个会话的并发读数（plan 0704 的 ADR-0006 D6）。 */
	inFlight: SftpInFlight,
};

/**  一次传输的**过 IPC 表示**。 */
export type SftpTransfer = {
	id: number,
	/**  从哪一栏、哪一个路径。 */
	from: SftpSide,
	fromPath: string,
	/**  到哪一栏、哪一个路径。 */
	to: SftpSide,
	toPath: string,
	state: SftpTransferState,
	/**
	 *  已经搬过去的字节数（传输中也读得到 —— 进度就是它）。
	 * 
	 *  ⚠️ `f64` 而不是 `u64`：同一个 BigInt 禁令（见 [`TransferId`]）。字节数是整数，
	 *  而 `f64` 到 2^53（九千太字节）都精确 —— 传不完的风险不存在，
	 *  换来的是前端不必碰 `BigInt`（那是 `JSON` 里根本没有的类型）。
	 */
	done: number | null,
	/**  源文件的大小（还没打开源之前是 0）。 */
	total: number | null,
	/**  失败原因（`state = failed` 时才有）。**字段值不虚构**（同 [`SftpSideInfo::failure`]）。 */
	failure: string | null,
	/**
	 *  目标那一栏是**经哪台直通**到达的（plan 0703 的 B 档）；`None` = 本机内存中转。
	 * 
	 *  记在这次传输上，而不是让读的人去看那一栏的现状：传输是历史记录，而一侧的连接事后
	 *  可能被换掉（换主机 / 重连）—— "这次走的是哪一档"不该跟着变。
	 */
	via: number | null,
};

/**  一次传输的状态。 */
export type SftpTransferState = 
/**  正在搬。 */
"running" | 
/**  成功 —— **目标端点的重命名已经落地**（"看到最终名就等于成功"，`scope.md` §4.2）。 */
"done" | 
/**  失败（原因在 [`SftpTransfer::failure`]）。 */
"failed" | 
/**  被取消（用户点的，或者 `Session` 被关）。 */
"cancelled";

/**  没动这一行的原因。**两个取值对应两个不同的下一步动作**（对用户说的是两句话）。 */
export type SkipReason = 
/**  池里已经有同名的行了（想换掉它就再导一次并选择覆盖）。 */
"existing" | 
/**  这一条是**为跳板补建**的，而池里已有同名行 —— 用的是池里那一行。 */
"fallback";

/**  看见了、但**没动**的一行。 */
export type SkippedHost = {
	name: string,
	reason: SkipReason,
};

/**  看见了、但**没动**的一条。 */
export type SkippedKey = {
	name: string,
	reason: BwImportSkip,
};

/**
 *  连接失败的类别。**前端据此决定"要不要让用户核对什么"** —— 不是把消息字符串
 *  拿去匹配（那是最容易在改文案时静默失效的一种判据）。
 */
export type SshFailureKind = 
/**  **服务端的密钥与记下来的不一样**（ADR-0003 D11 的警报，阶段 6 也不重连）。 */
"hostKeyChanged" | 
/**  用户否认了一把没见过的密钥 —— 与上一档分开：那是常态，这是明确拒绝。 */
"hostKeyRejected" | 
/**  没见过这把密钥，而没问成（超时 / 没人可问）。**不是"接受"的近义词**。 */
"hostKeyUnknown" | 
/**  库内的主机密钥缓存用不了（写了 / 读不出）—— 提示里那条"先解锁"多半是它。 */
"hostKeyCache" | 
/**  认证失败：我们有的方式都试过了。 */
"auth" | 
/**  连不上 / 超时 / 通道开不出来。 */
"connect" | 
/**
 *  **跳板这条线断了**（plan 0505）：链成环 / 过长，或者跳板机拒绝转发到目标。
 * 
 *  与 [`SshFailureKind::Connect`] 分开是刻意的：那一档是"我连不上**你挑的那台**"，
 *  这一档是"**跳板机**够不着它"。混在一起用户会去查自己的网络，而问题在对端。
 */
"jump" | 
/**  其余（错误消息里说得清）。 */
"other";

/**  IPC 边界的 SSH 错误。变体按**用户的下一步动作**分（见模块文档）。 */
export type SshIpcError = 
/**  库没解锁。**不连**：信任记录与密钥池都在库里，绕过去就等于把三态判定降成两态。 */
{ kind: "locked" } | 
/**  池里没有这一行（`id` 不存在，或者它引用的密钥不见了）。 */
{ kind: "noSuchHost"; detail: {
	id: number,
} } | 
/**  连接这条路失败。`kind` 是给界面分辨**警报**用的，`message` 是给人看的整句话。 */
{ kind: "failed"; detail: {
	kind: SshFailureKind,
	message: string,
} } | 
/**  内部状态不可用（runtime 起不来、会话表中毒、连接线程起不来）。 */
{ kind: "internal"; detail: {
	message: string,
} };

/**
 *  库文件的状态。**与 `crate::store::VaultState` 分开**：这是 IPC 类型（要生成 TS），
 *  而存储 crate 不该为了生成 TS 去依赖被 app 钉住版本的 `specta`。
 * 
 *  两边的映射写成穷尽 `match`（下面的 `From`）：存储层加了状态，**这里编译不过** ——
 *  而不是悄悄少一个分支，让前端在一个它不认识的值上做默认动作。
 * 
 *  ⚠️ 这个名字与 `tauri::State` 撞车，所以那几个签名里写全 `tauri::State<'_, Vault>` ——
 *  不为了省几个字把 IPC 类型改名（它已经出现在生成物里）。
 */
export type State = 
/**  文件不存在：还没有建过。解锁会**建一个新的**。 */
"missing" | 
/**
 *  文件在但是 **0 字节**：还没有密钥落在那里（这种文件用什么口令都能"打开"，
 *  见 ADR-0002 §7）。解锁同样会建一个新的。
 */
"empty" | 
/**  有内容。解锁会**打开它**（口令不对就打不开）。 */
"present";

/**
 *  一次"打开 / 重试"的结果。
 * 
 *  为什么不是 `Result<handle, error>`：连接失败时这条隧道**仍然登记着**（状态 `失败`，
 *  可手动重试 —— D12），界面因此必须拿到 `handle` 才说得清"是哪一条失败了"。
 *  把"根本没登记成"（库锁着 / 规则不存在）与"登记了但连不上"混进同一个 `Err`，
 *  前者会退化成一个没人能重试的死胡同。
 */
export type TunnelAttempt = {
	/**  这条隧道的句柄（无论连上没有，它都登记着）。 */
	handle: number,
	/**  连接失败的原因；`None` = 已连接。 */
	failure: TunnelError | null,
};

/**  IPC 边界的隧道错误。变体按**用户的下一步动作**分（同 `VaultError` / `SshIpcError`）。 */
export type TunnelError = 
/**  库没解锁。规则在库里，**没有别的来路**。 */
{ kind: "locked" } | 
/**  池里没有这一条规则。 */
{ kind: "noSuchForward"; detail: {
	id: number,
} } | 
/**  规则指向的那台主机不在池里。 */
{ kind: "noSuchHost"; detail: {
	id: number,
} } | 
/**  这个句柄不是一条隧道（已经停止 / 从来不存在）。 */
{ kind: "notATunnel"; detail: {
	handle: number,
} } | 
/**
 *  本地端口没拿到：被占用、无权限、绑定地址不可用。
 * 
 *  ⚠️ 它在一类失败里出现得最多（端口被占用），而且**发生在握手之前** ——
 *  用户不必先答完凭据才被告知端口没拿到。
 */
{ kind: "bind"; detail: {
	address: string,
	message: string,
} } | 
/**
 *  远端监听没拿到：服务端那个端口被它自己占着，或它不允许远端转发。
 * 
 *  与 [`Self::Bind`] 分开：那一条说的是"**本机**的端口没拿到"，用户腾一个端口就好；
 *  这一条要动的地方在**服务端** —— 在本机上做什么都没用。
 */
{ kind: "remoteBind"; detail: {
	address: string,
	message: string,
} } | 
/**
 *  动态转发（SOCKS5）的绑定地址不是回环地址。
 * 
 *  与 [`Self::Bind`] 分开：那一条是"这个端口没拿到"，换个端口就好；这一条是
 *  "这个地址**不许**绑" —— 换端口没有用，要改的是绑定的网卡范围。
 *  判据与理由见 `crate::ssh::socks5`（这一侧无认证）。
 */
{ kind: "notLoopback"; detail: {
	address: string,
} } | 
/**  连接这条路失败。`kind` 是给界面分辨**警报**用的（同 `SshIpcError`）。 */
{ kind: "failed"; detail: {
	kind: SshFailureKind,
	message: string,
} } | 
/**  状态转移被拒。多半是"另一条路已经把它推到终态了"，刷新一下即可。 */
{ kind: "transition"; detail: {
	message: string,
} } | 
/**  内部状态不可用。 */
{ kind: "internal"; detail: {
	message: string,
} };

/**
 *  **状态变化事件**（ADR-0003 D12 的"状态变化发事件"，事件名见 [`Self::NAME`]）。
 * 
 *  载荷带 `handle`（按 `SessionId` 路由的落点）而不只是状态：前端与托盘要能回答
 *  "是**哪一条**隧道失败了"—— 只报状态的话，多隧道并行时那份信息就丢了。
 */
export type TunnelStateChanged = {
	/**  哪条隧道。 */
	handle: number,
	/**  变成什么状态了。 */
	state: TunnelStateName,
	/**  重连次数（只有 `reconnecting` 带着它）。 */
	attempt: number | null,
};

/**
 *  状态过 IPC 的形状。
 * 
 *  与 `crate::tunnel::TunnelState` 分开：`Reconnecting` 的次数在那边是**载荷**，在这边是
 *  事件里的另一个字段（`attempt`）—— 前端因此不必对"每种状态长什么样"分支。
 *  映射写成穷尽 `match`：core 加一个状态时**这里编译不过**。
 */
export type TunnelStateName = "connecting" | "connected" | "reconnecting" | "failed" | "stopped";

/**
 *  解锁之后读一次四套池的结果。
 * 
 *  它存在的理由不是"给用户看几个数字"，而是让 `AGENTS.md` §7 那条"真实路径走通"
 *  有对象：真 app 上 `invoke` 出来的这份数字，正是**库真的被解开并读通了**的证据
 *  （只有拿到了正确的密钥才读得出行数）。
 */
export type VaultContents = {
	/**
	 *  计数是 `u32` 而不是 `usize`：生成器**拒绝**把 64 位整数导出成 TS
	 *  （BigInt 的精度问题，与问题 #32 同类）。这里不做 `as` 截断，而是 checked 转换。
	 */
	keys: number,
	hosts: number,
	serials: number,
	forwards: number,
};

/**
 *  取库的状态时可能出的错。
 * 
 *  与 `IpcError` 分开：域不同，前端能据此做的动作也不同（这里是"环境或口令的问题"，
 *  而不是"某个会话坏了"）。
 * 
 *  变体按**用户的下一步动作**合并（与 `StoreError::Conflict` 同一个理由）：
 *  版本不对 / 缺表 / 文件在半路被删了，对用户都是"这个库用不了，看消息"。
 */
export type VaultError = 
/**
 *  连数据目录都取不到（既没有便携目录，OS 数据目录也解析失败）。
 * 
 *  ⚠️ **不退回 OS 目录**（`portable.md` §2 第 3 条）：用户以为数据在 U 盘上、
 *  实际落在本地磁盘，比"明确报错"坏得多。
 */
{ kind: "noDataDir" } | 
/**  看文件状态这一步失败了（权限 / IO）。 */
{ kind: "io"; detail: {
	message: string,
} } | 
/**
 *  已经解开了。**不替换**：静默换掉一个正在用的连接，会让"我现在用的是哪把口令"
 *  变成一个没人答得上来的问题。
 */
{ kind: "alreadyUnlocked" } | 
/**
 *  打不开：口令错**或**文件不是本程序的库。SQLCipher 对这两者给同一个
 *  `SQLITE_NOTADB`，我们也不假装能区分（文案因此把两种可能都说出来）。
 */
{ kind: "wrongPassphrase" } | 
/**
 *  空口令。前端本该拦住，但**后端也不接受** —— 空 key 会让 SQLCipher 退化成明文库
 *  （ADR-0002 D5）。
 */
{ kind: "emptyPassphrase" } | 
/**
 *  口令比一页受保护内存还长（`crate::store::MAX_LEN`）。**不是截断**：
 *  截断会让"口令错了"变成一件没人能解释的事。
 */
{ kind: "passphraseTooLong"; detail: {
	max: number,
} } | 
/**
 *  **内存锁不住**（`mlock` 被拒）：`memsafe` 没有降级路径，所以解锁**不能进行**。
 * 
 *  这条必须是用户能懂的一句话，而不是一个错误码：它是"这台机器上你解不开自己的库"，
 *  下一步动作是查 `ulimit -l` / 容器里的 `RLIMIT_MEMLOCK`，而不是重试。
 */
{ kind: "notLockable"; detail: {
	message: string,
} } | 
/**
 *  库**锁着**，而这条路径需要一个解开的库。
 * 
 *  与 [`VaultError::AlreadyUnlocked`] 是一对：那个说"已经有连接了，别再开一个"，
 *  这个说"还没有连接，先解开"。目前只有 SSH 那条路会走到这里（它的信任记录与
 *  密钥池都在库里），但文案不写"SSH" —— 错误说的是**库的状态**，不是谁在问。
 */
{ kind: "locked" } | 
/**  这个库用不了：版本不认识、缺表、或者文件在半路没了。 */
{ kind: "unusable"; detail: {
	message: string,
} } | 
/**
 *  内部状态不可用（Mutex 中毒、阻塞任务 join 失败）。
 *  **不是用户错误**，但也不能 `unwrap`。
 */
{ kind: "internal"; detail: {
	message: string,
} };

/**  `vault_status` 的返回。 */
export type VaultStatus = {
	/**
	 *  库文件的路径（ADR-0002 D1：与 `config.json` 同一个数据目录）。
	 * 
	 *  它**是**绝对路径，而这与 P2 第 2 条（"库里不存绝对路径"）不冲突：那条禁止的是
	 *  **把路径存进库**（搬家后会静默失效），而这是运行时算出来给用户看的 ——
	 *  顺带回答"我的数据到底在哪"（`portable.md` §4）。
	 */
	path: string,
	state: State,
	/**
	 *  库**开着**没有（解密连接在不在）。与 `state` 是两件事：文件一直在，
	 *  而锁开了、又锁上了。
	 */
	unlocked: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

